name: Lint Python

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install vscode
        pip install webbrowser
        pip install pyperclip
        pip install bs4
        pip install requests

    - name: Run pylint
      run: |
        pylint extension.py
